export const FETCH_CITYLIST = 'FETCH_CITYLIST'
export const FETCH_CITYLIST_SUCCESS = 'FETCH_CITYLIST_SUCCESS'
export const FETCH_CITYLIST_ERROR = 'FETCH_CITYLIST_ERROR'
export const SELECT_CITY = 'SELECT_CITY'

export const FETCH_WEATHER = 'FETCH_WEATHER'
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS'
export const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR'